### ISSUE TITLE
集成implementation 'cn.jzvd:jiaozivideoplayer:7.2.3'之后，进到界面，点击播放崩溃

### ISSUE THREAD

**Issue by Dallur** [Jzvd/JZVideo#104]
2020-04-08 16:49:57.130 22710-22710/org.alluring.livedemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.alluring.livedemo, PID: 22710
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at cn.jzvd.JZMediaSystem.prepare(JZMediaSystem.java:34)
        at cn.jzvd.JZMediaSystem.onSurfaceTextureAvailable(JZMediaSystem.java:182)
        at android.view.TextureView.getTextureLayer(TextureView.java:400)
        at android.view.TextureView.draw(TextureView.java:349)
        at android.view.View.updateDisplayListIfDirty(View.java:20350)
        at android.view.View.draw(View.java:21205)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4412)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4171)
        at android.view.View.updateDisplayListIfDirty(View.java:20341)
        at android.view.View.draw(View.java:21205)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4412)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4171)
        at android.view.View.draw(View.java:21476)
        at android.view.View.updateDisplayListIfDirty(View.java:20350)
        at android.view.View.draw(View.java:21205)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4412)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4171)
        at android.view.View.updateDisplayListIfDirty(View.java:20341)
        at android.view.View.draw(View.java:21205)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4412)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4171)
        at android.view.View.updateDisplayListIfDirty(View.java:20341)
        at android.view.View.draw(View.java:21205)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4412)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4171)
        at android.view.View.updateDisplayListIfDirty(View.java:20341)
        at android.view.View.draw(View.java:21205)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4412)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4171)
        at android.view.View.updateDisplayListIfDirty(View.java:20341)
        at android.view.View.draw(View.java:21205)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4412)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4171)
        at android.view.View.updateDisplayListIfDirty(View.java:20341)
        at android.view.View.draw(View.java:21205)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4412)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4171)
        at android.view.View.updateDisplayListIfDirty(View.java:20341)
        at android.view.View.draw(View.java:21205)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4412)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4171)
        at android.view.View.updateDisplayListIfDirty(View.java:20341)
        at android.view.View.draw(View.java:21205)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4412)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4171)
        at android.view.View.draw(View.java:21476)
        at com.android.internal.policy.DecorView.draw(DecorView.java:831)
        at android.view.View.updateDisplayListIfDirty(View.java:20350)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3685)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3480)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2817)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1778)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7751)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
        at android.view.Choreographer.doCallbacks(Choreographer.java:865)
2020-04-08 16:49:57.130 22710-22710/org.alluring.livedemo E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:800)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2020-04-08 16:49:57.149 1614-4689/? E/InputDispatcher: Window handle WindowManager has no registered input channel
2020-04-08 16:49:57.155 1614-2361/? E/InputDispatcher: channel '798e9fb org.alluring.livedemo/org.alluring.livedemo.ui.JZPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-04-08 16:49:57.158 563-563/? E/SELinux: avc:  denied  { find } for interface=vendor.qti.hardware.servicetracker::IServicetracker sid=u:r:system_server:s0 pid=1614 scontext=u:r:system_server:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0

**Comment by Liberations** [comment]
app:build.gradle加入这句试试
compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
