### ISSUE TITLE
7.3.1 视频全屏返回 来回切换 crash

### ISSUE THREAD

**Issue by vonions** [Jzvd/JZVideo#151]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5628)
        at android.view.ViewGroup.removeViewAt(ViewGroup.java:5591)
        at cn.jzvd.Jzvd.gotoScreenNormal(Jzvd.java:974)
        at cn.jzvd.Jzvd.backPress(Jzvd.java:221)
        at cn.jzvd.JzvdStd.clickBack(JzvdStd.java:376)
        at cn.jzvd.JzvdStd.onClick(JzvdStd.java:296)
        at android.view.View.performClick(View.java:7213)
        at android.view.View.performClickInternal(View.java:7187)
        at android.view.View.access$3500(View.java:828)
        at android.view.View$PerformClick.run(View.java:27675)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)

先点击全屏，然后点击返回，来回切两次就crash 了。 然后退回7.2.0 ，一切正常

**Comment by lipangit** [comment]
保持关注，这可能是个很严重的问题

**Comment by BoxuanJia** [comment]
目前这个问题，我这边测试都是在release版本中出现，debug中没事。
怀疑是混淆造成的问题。

**Comment by vonions** [comment]
> 我这边发生过一样的问题，当时release中出现，debug中未出现。
> 所以考虑是混淆文件造成的。
> 解决办法是：
> **如果你自己定义类继承JzvdStd,请注意把你自己的这个类配置到混淆配置中，这个问题应该就没了。**

我没有混淆也不行，我现在用的7.2.0

**Comment by tangrun** [comment]
我也是出现混淆后全屏切换后闪退，报错信息与上面的日志相同。
据我排查应该是我用了微信的混淆插件把布局里类给混淆掉，as是默认把xml里面用到过的类都keep的，用插件后混淆掉所以会有问题，其他人自定义类继承Jzvd混淆后安装使用或许也会出现同样问题，可以加条混淆试试看能否解决问题
 -keep class * extends cn.jzvd.Jzvd {*; }

**Comment by lgst** [comment]
我也是混淆代码后出现这种问题，应该是跟混淆代码有关系
