### ISSUE TITLE
使用JZMediaExo 报 NullPointerException,非必现

### ISSUE THREAD

**Issue by zhw634631** [Jzvd/JZVideo#176]
**什么jzvd版本
v7.4.1
**什么播放器内核
JZMediaExo
**相关log是什么
无WIFI情况：
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.SimpleExoPlayer.addVideoListener(com.google.android.exoplayer2.video.VideoListener)' on a null object reference
        at com.tinytiger.titi.widget.video.JZMediaExo.lambda$prepare$0$JZMediaExo(JZMediaExo.java:101)
        at com.tinytiger.titi.widget.video.-$$Lambda$JZMediaExo$sQNhYEfigYA6pA91aHAt0PaQ7VM.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)

偶发情况,大概10次有一次报这个

**Comment by lipangit** [comment]
保持关注，就是最基础的exo用法



---原始邮件---
发件人: "zhw634631"<notifications@github.com&gt;
发送时间: 2020年6月19日(周五) 中午1:56
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 使用JZMediaExo 报 NullPointerException,非必现 (#176)




 
**什么jzvd版本
 v7.4.1
 **什么播放器内核
 JZMediaExo
 **相关log是什么
 无WIFI情况：
 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.SimpleExoPlayer.addVideoListener(com.google.android.exoplayer2.video.VideoListener)' on a null object reference
 at com.tinytiger.titi.widget.video.JZMediaExo.lambda$prepare$0$JZMediaExo(JZMediaExo.java:101)
 at com.tinytiger.titi.widget.video.-$$Lambda$JZMediaExo$sQNhYEfigYA6pA91aHAt0PaQ7VM.run(Unknown Source:4)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:214)
 at android.os.HandlerThread.run(HandlerThread.java:67)
 
偶发情况,大概10次有一次报这个
