### ISSUE TITLE
播放Assets里面的视频的时候点击全屏然后退出全屏会奔溃

### ISSUE THREAD

**Issue by zhumj** [Jzvd/JZVideo#210]
**什么jzvd版本
7.4.1
**什么播放器内核
默认
**相关log是什么
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5433)
at android.view.ViewGroup.removeViewAt(ViewGroup.java:5396)
at cn.jzvd.Jzvd.gotoNormalScreen(Jzvd.java:1000)
at cn.jzvd.Jzvd.backPress(Jzvd.java:223)
at cn.jzvd.JzvdStd.clickBack(JzvdStd.java:416)
at cn.jzvd.JzvdStd.onClick(JzvdStd.java:336)
at android.view.View.performClick(View.java:7171)
at android.view.View.performClickInternal(View.java:7148)
at android.view.View.access$3500(View.java:802)
at android.view.View$PerformClick.run(View.java:27409)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7626)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**demo是否有这个问题

**自己做了哪些修改
按照给出的模板Demo自定义播放器，播放Assets里面的视频
**如何操作复现
播放Assets里面的视频，点击全屏播放，然后退出全屏
**什么安卓版本，什么机型
安卓Q
**截图或者视频说明情况

**Comment by xxxifan** [comment]
为啥关闭了，是解决了吗？
我也遇到这个问题，没有思路。

**Comment by zhumj** [comment]
> 为啥关闭了，是解决了吗？
> 我也遇到这个问题，没有思路。

我的是因为在RecyclerView播放，全屏返回的时候
```
 recyclerView.addOnChildAttachStateChangeListener(object : OnChildAttachStateChangeListener {
            override fun onChildViewDetachedFromWindow(view: View) {
                try {
                    val jzvd: Jzvd = view.findViewById(R.id.jzVideoPlayer)
                    if (Jzvd.CURRENT_JZVD != null &&
                        jzvd.jzDataSource.containsTheUrl(Jzvd.CURRENT_JZVD.jzDataSource.currentUrl)
                    ) {
                        if (Jzvd.CURRENT_JZVD != null && Jzvd.CURRENT_JZVD.screen != Jzvd.SCREEN_FULLSCREEN) {
                            Jzvd.releaseAllVideos()
                        }
                    }
                } catch (e: Exception) {
                    e.printStackTrace()
                }
            }

        })
```
onChildViewDetachedFromWindow 方法里面的 val jzvd: Jzvd = view.findViewById(R.id.jzVideoPlayer) 找不到这个控件，我加个tyr-catch就行了。
