### ISSUE TITLE
JzvdStdVolume 偶现崩溃

### ISSUE THREAD

**Issue by xiaochandou** [Jzvd/JZVideo#247]
jzvd 版本4.7.1

我把demo 中的JzvdStdVolume 直接拷贝到项目中用的 ,自测没发现任何问题.
在友盟上看到了错误日志:
k_ac:SystemException
k_ct:exception
Exception message:
Back traces starts.
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
    at cn.jzvd.JZMediaSystem.start(JZMediaSystem.java:60)
    at cn.jzvd.Jzvd.onPrepared(Jzvd.java:552)
    at com.****.****.widget.JzvdStdVolume.onPrepared(JzvdStdVolume.java:45)
    at cn.jzvd.JZMediaSystem.lambda$onPrepared$6$JZMediaSystem(JZMediaSystem.java:138)
    at cn.jzvd.-$$Lambda$JZMediaSystem$zIW9UuYfRsLvwe6Lu-iDTY-nGW8.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8347)
    at java.lang.reflect.Method.invoke(Native Method)

**Comment by lipangit** [comment]
保持关注



---原始邮件---
发件人: "xiaochandou"<notifications@github.com&gt;
发送时间: 2020年9月29日(周二) 上午10:14
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] JzvdStdVolume 偶现崩溃 (#247)




 
jzvd 版本4.7.1
 
我把demo 中的JzvdStdVolume 直接拷贝到项目中用的 ,自测没发现任何问题.
 在友盟上看到了错误日志:
 k_ac:SystemException
 k_ct:exception
 Exception message:
 Back traces starts.
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
 at cn.jzvd.JZMediaSystem.start(JZMediaSystem.java:60)
 at cn.jzvd.Jzvd.onPrepared(Jzvd.java:552)
 at com...widget.JzvdStdVolume.onPrepared(JzvdStdVolume.java:45)
 at cn.jzvd.JZMediaSystem.lambda$onPrepared$6$JZMediaSystem(JZMediaSystem.java:138)
 at cn.jzvd.-$$Lambda$JZMediaSystem$zIW9UuYfRsLvwe6Lu-iDTY-nGW8.run(Unknown Source:2)
 at android.os.Handler.handleCallback(Handler.java:900)
 at android.os.Handler.dispatchMessage(Handler.java:103)
 at android.os.Looper.loop(Looper.java:219)
 at android.app.ActivityThread.main(ActivityThread.java:8347)
 at java.lang.reflect.Method.invoke(Native Method)

**Comment by ZhaoYidong** [comment]
类似的问题。
版本：7.6.0

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
       at cn.jzvd.JZMediaSystem.start(JZMediaSystem.java:61)
       at cn.jzvd.Jzvd.onPrepared(Jzvd.java:568)
       at cn.jzvd.JZMediaSystem.lambda$onPrepared$6(JZMediaSystem.java:139)
       at cn.jzvd.-$$Lambda$JZMediaSystem$zIW9UuYfRsLvwe6Lu-iDTY-nGW8.run(-.java)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6577)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:986)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
