### ISSUE TITLE
播放视频时有电话打入报线程错误

### ISSUE THREAD

**Issue by PerfectlifeNSen** [Jzvd/JZVideo#251]
2020-10-09 19:22:28.240 24035-24128/com.iwthvyg.cvnyrit E/AndroidRuntime: FATAL EXCEPTION: excHandlerThread
    Process: com.iwthvyg.cvnyrit, PID: 24035
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8785)
        at android.view.ViewRootImpl.playSoundEffect(ViewRootImpl.java:7397)
        at android.view.View.playSoundEffect(View.java:24174)
        at android.view.View.performClick(View.java:6983)
        at cn.jzvd.Jzvd$1.onAudioFocusChange(Jzvd.java:83)
        at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2342)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by lipangit** [comment]
是个问题，研究处理

**Comment by Liberations** [comment]
demo没这问题

**Comment by jkjay** [comment]
我也出现这个报错了

**Comment by Liberations** [comment]
重点是这句 Only the original thread that created a view hierarchy can touch its views 好好分析下

**Comment by HysonHou** [comment]
特意打电话测了一下，三星s10e不会哦。应该是部分机型

**Comment by Kwanloyal** [comment]
> 我也出现这个报错了

这个问题似乎也没修复

**Comment by mlp1995** [comment]
部分机型 audioManager 的回调回调在子线程
