### ISSUE TITLE
继承JzvdStd 没做任何事情 直接崩溃了

### ISSUE THREAD

**Issue by KwanTang324** [Jzvd/JZVideo#261]
**什么jzvd版本
7.4.2
**什么播放器内核
没改，简单的使用方式
![image](https://user-images.githubusercontent.com/20396159/97249151-3d467a00-183e-11eb-877e-69e2701bece1.png)

**相关log是什么
TinkerUncaughtHandler catch exception:java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5485)
        at android.view.ViewGroup.removeViewAt(ViewGroup.java:5448)
        at cn.jzvd.Jzvd.gotoNormalScreen(Jzvd.java:1003)
        at cn.jzvd.Jzvd.backPress(Jzvd.java:234)
        at cn.jzvd.Jzvd.clickFullscreen(Jzvd.java:358)
        at cn.jzvd.Jzvd.onClick(Jzvd.java:349)
        at cn.jzvd.JzvdStd.onClick(JzvdStd.java:326)
        at android.view.View.performClick(View.java:7188)
        at android.view.View.performClickInternal(View.java:7165)
        at android.view.View.access$3500(View.java:814)
        at android.view.View$PerformClick.run(View.java:27651)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:230)
        at android.app.ActivityThread.main(ActivityThread.java:7768)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:508)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
**demo是否有这个问题
不继承Jzvdstd则没有问题
**自己做了哪些修改
![image](https://user-images.githubusercontent.com/20396159/97248763-6b778a00-183d-11eb-9bf4-5a47e0454509.png)

**如何操作复现
点击全屏，退出全屏，再点击全屏，崩溃
**什么安卓版本，什么机型
任意版本 任意机型
**截图或者视频说明情况

**Comment by lipangit** [comment]
复现频率如何



---原始邮件---
发件人: "KwanTang"<notifications@github.com&gt;
发送时间: 2020年10月27日(周二) 上午10:22
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 继承JzvdStd 没做任何事情 直接崩溃了 (#261)




 
**什么jzvd版本
 7.4.2
 **什么播放器内核
 没改，简单的使用方式
 
 
**相关log是什么
 TinkerUncaughtHandler catch exception:java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
 at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5485)
 at android.view.ViewGroup.removeViewAt(ViewGroup.java:5448)
 at cn.jzvd.Jzvd.gotoNormalScreen(Jzvd.java:1003)
 at cn.jzvd.Jzvd.backPress(Jzvd.java:234)
 at cn.jzvd.Jzvd.clickFullscreen(Jzvd.java:358)
 at cn.jzvd.Jzvd.onClick(Jzvd.java:349)
 at cn.jzvd.JzvdStd.onClick(JzvdStd.java:326)
 at android.view.View.performClick(View.java:7188)
 at android.view.View.performClickInternal(View.java:7165)
 at android.view.View.access$3500(View.java:814)
 at android.view.View$PerformClick.run(View.java:27651)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:230)
 at android.app.ActivityThread.main(ActivityThread.java:7768)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:508)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
 **demo是否有这个问题
 不继承Jzvdstd则没有问题
 **自己做了哪些修改
 
 
**如何操作复现
 点击全屏，退出全屏，再点击全屏，崩溃
 **什么安卓版本，什么机型
 任意版本 任意机型
 **截图或者视频说明情况

**Comment by xxxifan** [comment]
我们线上app持续收到这个崩溃，概率不大但一直都有，覆盖机型和安卓版本都比较广泛

**Comment by Liberations** [comment]
see #327
