### ISSUE TITLE
手机音乐软件播放音乐，ActivityTikTok列表滑动切换播放，播放会暂停，有的点击播放按钮无效state == 4 报错为java.lang.IllegalStateException: Handler (android.os.Handler) {62a45a9} sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by 30Code** [Jzvd/JZVideo#269]
java.lang.IllegalStateException: Handler (android.os.Handler) {62a45a9} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:654)
        at android.os.Handler.enqueueMessage(Handler.java:769)
        at android.os.Handler.sendMessageAtTime(Handler.java:718)
        at android.os.Handler.sendMessageDelayed(Handler.java:688)
        at android.os.Handler.post(Handler.java:405)
        at cn.jzvd.JZMediaSystem.start(JZMediaSystem.java:61)
        at cn.jzvd.Jzvd.startVideoAfterPreloading(Jzvd.java:585)
        at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ActivityTikTok.autoPlayVideo(ActivityTikTok.java:89)
        at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ActivityTikTok.access$000(ActivityTikTok.java:17)
        at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ActivityTikTok$1.onPageSelected(ActivityTikTok.java:59)
        at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ViewPagerLayoutManager.onScrollStateChanged(ViewPagerLayoutManager.java:87)
        at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5197)
        at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1550)
        at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5397)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:893)
        at android.view.Choreographer.doFrame(Choreographer.java:809)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by lipangit** [comment]
复现频率如何



---原始邮件---
发件人: "30Code"<notifications@github.com&gt;
发送时间: 2020年11月17日(周二) 下午4:32
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 手机音乐软件播放音乐，ActivityTikTok列表滑动切换播放，播放会暂停，有的点击播放按钮无效state == 4 报错为java.lang.IllegalStateException: Handler (android.os.Handler) {62a45a9} sending message to a Handler on a dead thread (#269)




 
java.lang.IllegalStateException: Handler (android.os.Handler) {62a45a9} sending message to a Handler on a dead thread
 at android.os.MessageQueue.enqueueMessage(MessageQueue.java:654)
 at android.os.Handler.enqueueMessage(Handler.java:769)
 at android.os.Handler.sendMessageAtTime(Handler.java:718)
 at android.os.Handler.sendMessageDelayed(Handler.java:688)
 at android.os.Handler.post(Handler.java:405)
 at cn.jzvd.JZMediaSystem.start(JZMediaSystem.java:61)
 at cn.jzvd.Jzvd.startVideoAfterPreloading(Jzvd.java:585)
 at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ActivityTikTok.autoPlayVideo(ActivityTikTok.java:89)
 at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ActivityTikTok.access$000(ActivityTikTok.java:17)
 at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ActivityTikTok$1.onPageSelected(ActivityTikTok.java:59)
 at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ViewPagerLayoutManager.onScrollStateChanged(ViewPagerLayoutManager.java:87)
 at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5197)
 at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1550)
 at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5397)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
 at android.view.Choreographer.doCallbacks(Choreographer.java:893)
 at android.view.Choreographer.doFrame(Choreographer.java:809)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
 at android.os.Handler.handleCallback(Handler.java:907)
 at android.os.Handler.dispatchMessage(Handler.java:105)
 at android.os.Looper.loop(Looper.java:216)
 at android.app.ActivityThread.main(ActivityThread.java:7625)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by 30Code** [comment]
很容易复现，列表多滑动几次就复现了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jzvd/JZVideo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月17日(星期二) 晚上8:22
收件人:&nbsp;"Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送:&nbsp;"NathLine"<nathline1029@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Jzvd/JZVideo] 手机音乐软件播放音乐，ActivityTikTok列表滑动切换播放，播放会暂停，有的点击播放按钮无效state == 4 报错为java.lang.IllegalStateException: Handler (android.os.Handler) {62a45a9} sending message to a Handler on a dead thread (#269)





 复现频率如何 
 
 
 
 ---原始邮件--- 
 发件人: "30Code"<notifications@github.com&amp;gt; 
 发送时间: 2020年11月17日(周二) 下午4:32 
 收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: [Jzvd/JZVideo] 手机音乐软件播放音乐，ActivityTikTok列表滑动切换播放，播放会暂停，有的点击播放按钮无效state == 4 报错为java.lang.IllegalStateException: Handler (android.os.Handler) {62a45a9} sending message to a Handler on a dead thread (#269) 
 
 
 
 
   
 java.lang.IllegalStateException: Handler (android.os.Handler) {62a45a9} sending message to a Handler on a dead thread 
  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:654) 
  at android.os.Handler.enqueueMessage(Handler.java:769) 
  at android.os.Handler.sendMessageAtTime(Handler.java:718) 
  at android.os.Handler.sendMessageDelayed(Handler.java:688) 
  at android.os.Handler.post(Handler.java:405) 
  at cn.jzvd.JZMediaSystem.start(JZMediaSystem.java:61) 
  at cn.jzvd.Jzvd.startVideoAfterPreloading(Jzvd.java:585) 
  at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ActivityTikTok.autoPlayVideo(ActivityTikTok.java:89) 
  at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ActivityTikTok.access$000(ActivityTikTok.java:17) 
  at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ActivityTikTok$1.onPageSelected(ActivityTikTok.java:59) 
  at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ViewPagerLayoutManager.onScrollStateChanged(ViewPagerLayoutManager.java:87) 
  at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5197) 
  at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1550) 
  at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5397) 
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092) 
  at android.view.Choreographer.doCallbacks(Choreographer.java:893) 
  at android.view.Choreographer.doFrame(Choreographer.java:809) 
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078) 
  at android.os.Handler.handleCallback(Handler.java:907) 
  at android.os.Handler.dispatchMessage(Handler.java:105) 
  at android.os.Looper.loop(Looper.java:216) 
  at android.app.ActivityThread.main(ActivityThread.java:7625) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by 30Code** [comment]
出现state为4比较难复现，滑动列表播放界面经常会出现暂停按钮，不会自动播放，要怎么处理呢？



---原始邮件---
发件人: "Nathen"<notifications@github.com&gt;
发送时间: 2020年11月17日(周二) 晚上8:22
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"30Code"<nathline1029@qq.com&gt;;
主题: Re: [Jzvd/JZVideo] 手机音乐软件播放音乐，ActivityTikTok列表滑动切换播放，播放会暂停，有的点击播放按钮无效state == 4 报错为java.lang.IllegalStateException: Handler (android.os.Handler) {62a45a9} sending message to a Handler on a dead thread (#269)




 复现频率如何 
 
 
 
 ---原始邮件--- 
 发件人: "30Code"<notifications@github.com&amp;gt; 
 发送时间: 2020年11月17日(周二) 下午4:32 
 收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: [Jzvd/JZVideo] 手机音乐软件播放音乐，ActivityTikTok列表滑动切换播放，播放会暂停，有的点击播放按钮无效state == 4 报错为java.lang.IllegalStateException: Handler (android.os.Handler) {62a45a9} sending message to a Handler on a dead thread (#269) 
 
 
 
 
   
 java.lang.IllegalStateException: Handler (android.os.Handler) {62a45a9} sending message to a Handler on a dead thread 
  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:654) 
  at android.os.Handler.enqueueMessage(Handler.java:769) 
  at android.os.Handler.sendMessageAtTime(Handler.java:718) 
  at android.os.Handler.sendMessageDelayed(Handler.java:688) 
  at android.os.Handler.post(Handler.java:405) 
  at cn.jzvd.JZMediaSystem.start(JZMediaSystem.java:61) 
  at cn.jzvd.Jzvd.startVideoAfterPreloading(Jzvd.java:585) 
  at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ActivityTikTok.autoPlayVideo(ActivityTikTok.java:89) 
  at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ActivityTikTok.access$000(ActivityTikTok.java:17) 
  at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ActivityTikTok$1.onPageSelected(ActivityTikTok.java:59) 
  at cn.jzvd.demo.Tab_3_List.ListView.tiktok.ViewPagerLayoutManager.onScrollStateChanged(ViewPagerLayoutManager.java:87) 
  at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5197) 
  at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1550) 
  at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5397) 
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092) 
  at android.view.Choreographer.doCallbacks(Choreographer.java:893) 
  at android.view.Choreographer.doFrame(Choreographer.java:809) 
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078) 
  at android.os.Handler.handleCallback(Handler.java:907) 
  at android.os.Handler.dispatchMessage(Handler.java:105) 
  at android.os.Looper.loop(Looper.java:216) 
  at android.app.ActivityThread.main(ActivityThread.java:7625) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by 30Code** [comment]
华硕 ROG Phone 2（android Q） 播放QQ音乐同时，去切换视频抖音列表，后退出列表页，很容易复现播放器释放不掉（Jzvd.releaseAllVideos），视频声音还在播放的情况。

**Comment by Liberations** [comment]
参考 #77
