### ISSUE TITLE
tiktok列表自动播放失败

### ISSUE THREAD

**Issue by LDJHXM** [Jzvd/JZVideo#77]
最新版本和7.2.1都有这个问题

tiktok列表自动播放 第一条播放成功 第二条失败 第三条成功 第四条失败

播放失败的再次点击才能继续播放

demo apk一样的问题

手机型号 华为mate30  AndroidQ

**Comment by lipangit** [comment]
什么log。我这边一直成功。有什么猜测或者线索吗



---原始邮件---
发件人: "LDJHXM"<notifications@github.com&gt;
发送时间: 2020年3月18日(周三) 下午4:49
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] tiktok列表自动播放失败 (#77)




 
最新版本和7.2.1都有这个问题
 
tiktok列表自动播放 第一条播放成功 第二条失败 第三条成功 第四条失败
 
播放失败的再次点击才能继续播放
 
demo apk一样的问题
 
手机型号 华为mate30  AndroidQ

**Comment by LDJHXM** [comment]
~~之前跑你的apk试了几次都是隔条播放就失败  必现的   刚刚换了个网络就OK了  换网络回去也重现不了了   可能是和网络波动有关? 但是之前隔条能自动播放成功~ @lipangit

**Comment by lipangit** [comment]
没有log很难找到原因，保持关注。



---原始邮件---
发件人: "LDJHXM"<notifications@github.com&gt;
发送时间: 2020年3月18日(周三) 下午5:52
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] tiktok列表自动播放失败 (#77)




 
~~之前跑你的apk试了几次都是隔条播放就失败  必现的   刚刚换了个网络就OK了  换网络回去也重现不了了   可能是和网络波动有关? 但是之前隔条能自动播放成功~ @lipangit

**Comment by LDJHXM** [comment]
早上一看又复现了  
2020-03-19 10:31:36.486 19267-20659/com.qingke.hike W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.prepareAsync()' on a null object reference
2020-03-19 10:31:36.487 19267-20659/com.qingke.hike W/System.err:     at cn.jzvd.JZMediaSystem.lambda$prepare$0$JZMediaSystem(JZMediaSystem.java:53)
2020-03-19 10:31:36.487 19267-20659/com.qingke.hike W/System.err:     at cn.jzvd.-$$Lambda$JZMediaSystem$1SfpWnrQJjBakrZ3K2nGWWoyock.run(Unknown Source:2)
2020-03-19 10:31:36.487 19267-20659/com.qingke.hike W/System.err:     at android.os.Handler.handleCallback(Handler.java:888)
2020-03-19 10:31:36.487 19267-20659/com.qingke.hike W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2020-03-19 10:31:36.487 19267-20659/com.qingke.hike W/System.err:     at android.os.Looper.loop(Looper.java:213)
2020-03-19 10:31:36.487 19267-20659/com.qingke.hike W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)

穿插着
2020-03-19 10:33:31.643 19267-20781/com.qingke.hike W/MediaPlayer: Use of stream types is deprecated for operations other than volume control
2020-03-19 10:33:31.643 19267-20781/com.qingke.hike W/MediaPlayer: See the documentation for what to use instead with android.media.AudioAttributes to qualify your playback use case
2020-03-19 10:33:31.643 19267-20781/com.qingke.hike W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder

现在是必现的 日志只有这个警告 @lipangit

**Comment by lipangit** [comment]
提交给开发者了，一起解决

**Comment by lipangit** [comment]
有啥思路吗

**Comment by LDJHXM** [comment]
没有什么头绪  有时候是必现的 有时候就没了~播放失败报的日志就是以上的信息~  估计和我的网络环境有关吧

**Comment by LDJHXM** [comment]
我找到问题了 原因是我先播放着网易云音乐 然后再去打开视频列表 这时音乐停了 但是列表就会出现隔着一个才能自动播放成功的问题了 demo的例子也是这样 如果不播放音乐直接打开的话就可以 播放音乐在去打开视频列表就会出现这个BUG @lipangit

**Comment by lipangit** [comment]
这是个bug



---原始邮件---
发件人: "LDJHXM"<notifications@github.com&gt;
发送时间: 2020年4月6日(周一) 下午3:13
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] tiktok列表自动播放失败 (#77)




 
我找到问题了 原因是我先播放着网易云音乐 然后再去打开视频列表 这时音乐停了 但是列表就会出现隔着一个才能自动播放成功的问题了 demo的例子也是这样 如果不播放音乐直接打开的话就可以 播放音乐在去打开视频列表就会出现这个BUG @lipangit

**Comment by LDJHXM** [comment]
嗯 播放着音乐再去打开视频列表就会出现这个 我这边是必现的 不播放音乐的情况下是正常的

**Comment by lipangit** [comment]
帮忙研究一下吧&nbsp; 有点忙。我通知一下作者，看看他有没有啥想法



---原始邮件---
发件人: "LDJHXM"<notifications@github.com&gt;
发送时间: 2020年4月6日(周一) 下午4:18
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] tiktok列表自动播放失败 (#77)




 
嗯 播放着音乐再去打开视频列表就会出现这个 我这边是必现的 不播放音乐的情况下是正常的

**Comment by Liberations** [comment]
可尝试修改 startVideo中 requestAudioFocus的标志 AudioManager.AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK支持多路音频同时播放。
