### ISSUE TITLE
at cn.jzvd.JzvdStd.unregisterWifiListener(JzvdStd.java:888)

### ISSUE THREAD

**Issue by AfterChristmas** [Jzvd/JZVideo#96]
**什么jzvd版本
 implementation 'cn.jzvd:jiaozivideoplayer:7.2.3'
**相关log是什么
 Caused by: java.lang.IllegalArgumentException: Receiver not registered: cn.jzvd.JzvdStd$3@6a54942
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:821)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1230)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:587)
        at cn.jzvd.JzvdStd.unregisterWifiListener(JzvdStd.java:888)
        at cn.jzvd.JzvdStd.reset(JzvdStd.java:832)
        at cn.jzvd.Jzvd.releaseAllVideos(Jzvd.java:1017)
        at com.yingbao.career.video.tools.ActivityApiUIBigChangeAG.onDestroy(ActivityApiUIBigChangeAG.java:136)
        at android.app.Activity.performDestroy(Activity.java:6668)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4080)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4111) 
        at android.app.ActivityThread.access$1700(ActivityThread.java:170) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:179) 
        at android.app.ActivityThread.main(ActivityThread.java:5769) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674) 

**demo是否有这个问题
有
**自己做了哪些修改

**如何操作复现
关闭网络，打开ActivityApiUIBigChangeAG页面，进度条还在转圈，点击返回，崩溃
**什么安卓版本，什么机型
6.0  oppo a57
**截图或者视频说明情况

**Comment by lipangit** [comment]
有没有一种方法在unregisterReceiver之前检测一下是注册情况，避免这种错误。
